// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANJfJt5Iw7SR1iua6MTzao9ONRsSrL8XM',
    appId: '1:414693486859:web:4a006315216b32ca99720e',
    messagingSenderId: '414693486859',
    projectId: 'note-app-745a6',
    authDomain: 'note-app-745a6.firebaseapp.com',
    storageBucket: 'note-app-745a6.appspot.com',
    measurementId: 'G-XMLKWDQV19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIc_CkHOuwaOCHtE_Qh1uaGSxoHFhR4FI',
    appId: '1:414693486859:android:beeffb5cd460cc5799720e',
    messagingSenderId: '414693486859',
    projectId: 'note-app-745a6',
    storageBucket: 'note-app-745a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmu-rfKbWuOYexTv_lbMqKmM4NZCn1zMQ',
    appId: '1:414693486859:ios:314155aff8b89d9a99720e',
    messagingSenderId: '414693486859',
    projectId: 'note-app-745a6',
    storageBucket: 'note-app-745a6.appspot.com',
    iosBundleId: 'com.example.noteAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmu-rfKbWuOYexTv_lbMqKmM4NZCn1zMQ',
    appId: '1:414693486859:ios:e571f54d74484e4b99720e',
    messagingSenderId: '414693486859',
    projectId: 'note-app-745a6',
    storageBucket: 'note-app-745a6.appspot.com',
    iosBundleId: 'com.example.noteAppWithFirebase.RunnerTests',
  );
}
